; Seengreat RGB Matrix Adapter (E) Rev 1.2 + ESP32-S3 N16R8
; DevKit-pinnar 35/36/37 avklippta och bryggade från GPIO 9/10/11

[platformio]
default_envs = seengreat_v1_s3_n16r8_rewired

[env:seengreat_v1_s3_n16r8_rewired]
extends = env:esp32s3dev_16MB_opi
custom_usermods =
build_flags = ${common.build_flags} ${esp32s3.build_flags} ${hub75.build_flags} ${hub75.s3_build_flags} ${hub75.i2s_disable_flags}
  -D WLED_RELEASE_NAME=\"ESP32-S3_16MB_opi_Seengreat_V1_rewired\"
  -D SEENGREAT_V1_S3_REWIRED_PINOUT
  -D BTNPIN=-1 -D RLYPIN=-1 -D IRPIN=-1
lib_deps = ${esp32s3.lib_deps}
  ${hub75.lib_deps}
